apiVersion: v1
kind: Pod
metadata:
  name: nginx-simplenfsplugin
spec:
  containers:
  - image: maersk/nginx
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/www
        name: data-simplenfsplugin 
  volumes:
  - name: data-simplenfsplugin
    persistentVolumeClaim:
      claimName: data-simplenfsplugin 
