apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-simplenfsplugin
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-simplenfs-sc
