name: Darwin
on:
    pull_request: {}
    push: {}
jobs:
  build:
    name: Unit Tests
    runs-on: macos-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: ^1.16
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Run unit tests
      run: |
        go version
        go test -v -race ./pkg/...
