name: k8s api version check
on:
    pull_request: {}
    push: {}

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    # https://pluto.docs.fairwinds.com/advanced/#display-options
    - name: Download pluto
      uses: FairwindsOps/pluto/github-action@dcdabde6b68d6f9117fa97361bbc1e25e68df8aa # v5.23.5

    - name: Check deploy folder
      run: |
        pluto detect-files -d deploy

    - name: Check example folder
      run: |
        pluto detect-files -d deploy/example
