name: ShellCheck
on:
  push:
    tags:
      - v*
    branches:
      - master
      - release-*
  pull_request:
    branches:
      - master
      - release-*

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca # master
      env:
         SHELLCHECK_OPTS: -e SC2034
      with:
        severity: warning
        check_together: 'yes'
        disable_matcher: false
        ignore_paths: vendor release-tools hack
        format: gcc
