name: Static Checks
on:
    pull_request: {}
    push: {}
jobs:
    go_lint:
        name: Go Lint
        runs-on: ubuntu-latest
        steps:
            - name: Set up Go 1.x
              uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
              with:
                go-version: ^1.19
            - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
            - name: Run linter
              uses: golangci/golangci-lint-action@9fae48acfc02a90574d7c304a1758ef9895495fa # v7
              with:
                  version: v2.10
                  args: -E=errcheck,govet,unused,ineffassign,staticcheck,revive,misspell,asciicheck,bodyclose,dogsled,durationcheck,errname,forbidigo --timeout=30m0s
    verify-helm:
        name: Verify Helm
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
            - name: Verify Helm
              run: |
                sudo snap install yq
                sudo hack/verify-helm-chart.sh
