name: Windows Tests
on:
    pull_request: {}
    push: {}
jobs:
  build:
    strategy:
      matrix:
        go: [ '^1.16' ]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run Windows Unit Tests
        run: |
          go version
          go test -v -race ./pkg/...
